eureka:
  instance:
    hostname: service-registry
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka


spring:
  zipkin:
    base-url: http://ms-zipkin:9411
  sleuth:
    sampler:
      probability: 1.0