server:
  port: 8070
spring:
  profiles:
    active: docker
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/order
    username: postgres
    password: murat123
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: orderConfirmation:com.muratkistan.order_service.kafka.OrderConfirmation

application:
  config:
    customer-url: http://localhost:8020/api/v1/customers
    payment-url: http://localhost:8020/api/v1/payments
    product-url: http://localhost:8020/api/v1/products



---
spring:
  config:
    activate:
      on-profile: docker

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ms-postgre:5432/order
    username: muratkistan
    password: muratkistan

  kafka:
    producer:
      bootstrap-servers: ms-kafka:9092

application:
  config:
    customer-url: http://api-gateway:8020/api/v1/customers
    payment-url: http://api-gateway:8020/api/v1/payments
    product-url: http://api-gateway:8020/api/v1/products