server:
  port: 8060
spring:
  profiles:
    active: docker
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/payment
    username: postgres
    password: murat123
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: paymentConfirmation:com.muratkistan.payment_service.notification.PaymentNotificationRequest
application:
  config:
    product-url: http://localhost:8020/api/v1/products



---
spring:
  config:
    activate:
      on-profile: docker

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ms-postgre:5432/payment
    username: muratkistan
    password: muratkistan
    jpa:
      hibernate:
        ddl-auto: update
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    producer:
      bootstrap-servers: ms-kafka:9092

application:
  config:
    product-url: http://api-gateway:8020/api/v1/products